apiVersion: apps/v1
kind: Deployment
metadata:
  name: overops-server-deployment
  labels:
    app: overops-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: overops-server
  template:
    metadata:
      labels:
        app: overops-server
    spec:
      containers:
        - name: overops-server
          image: 432746435694.dkr.ecr.us-east-1.amazonaws.com/overops-server:latest
          ports:
            - containerPort: 8080
          env:
            - name: HOST_URL
              value: "overops-server-service"
            - name: FRONTEND_URL
              value: "poc-k8s.overops-samples.com"
            - name: DB_TYPE
              value: "mysql"
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: overops-server-db
                  key: url
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: overops-server-db
                  key: user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: overops-server-db
                  key: pass
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
          volumeMounts:
            - mountPath: /opt/private
              name: overops-server-private-volume
            - mountPath: /opt/takipi-server/storage
              name: overops-server-data-volume
      volumes:
        - name: overops-server-private-volume
          secret:
            secretName: overops-server
        - name: overops-server-data-volume
          nfs:
            server: fs-cab39c2b.efs.us-east-1.amazonaws.com
            path: /poc-storage

