apiVersion: apps/v1
kind: Deployment
metadata:
  name: overops-server-deployment
  labels:
    app: overops-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: overops-server
  template:
    metadata:
      labels:
        app: overops-server
    spec:
      containers:
        - name: overops-server
          image: overops/server:latest
          ports:
            - containerPort: 8080
          env:
            - name: HOST_URL
              value: "overops-server-service"
            - name: FRONTEND_URL
              value: "https://overops.example.com"
            - name: DB_TYPE
              value: "mysql"
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: overops-server-db
                  key: url
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: overops-server-db
                  key: user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: overops-server-db
                  key: pass
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "500m"
              memory: "8Gi"
            limits:
              cpu: "10000m"
              memory: "32Gi"
          volumeMounts:
            - mountPath: /opt/private
              name: overops-server-private-volume
            - mountPath: /opt/takipi-server/storage
              name: overops-server-data-volume
          # livenessProbe:
          #   httpGet:
          #     path: /service/png
          #     port: 8080
          #   initialDelaySeconds: 240
          #   periodSeconds: 10
          #   timeoutSeconds: 1
          #   failureThreshold: 3
      volumes:
        - name: overops-server-private-volume
          secret:
            secretName: overops-server
        - name: overops-server-data-volume
          hostPath:
            path: /local/path/to/storage
---
kind: Service
apiVersion: v1
metadata:
  name: overops-server-service
spec:
  selector:
    app: overops-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
