kind: Service
apiVersion: v1
metadata:
  name: overops-server-service-ext
  labels:
    dns: route53
  annotations:
    domainName: "poc-k8s.overops-samples.com"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: |-
      arn:aws:acm:us-east-1:432746435694:certificate/b9abcc49-8e59-4797-ab8c-877a78ddb71f
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  selector:
    app: overops-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8080
      name: https
---
kind: Service
apiVersion: v1
metadata:
  name: overops-server-service
spec:
  selector:
    app: overops-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080