apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-clinic-deployment
  labels:
    app: pet-clinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet-clinic
  template:
    metadata:
      labels:
        app: pet-clinic
        takipi: inject-agent
    spec:
      containers:
      - image: pet-clinic
        name: pet-clinic
        imagePullPolicy: Never
