kind: Service
apiVersion: v1
metadata:
  name: overops-storage-service
spec:
  selector:
    app: overops-storage-server
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
    name: storage-server
