apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-generator-deployment
  labels:
    app: event-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-generator
  template:
    metadata:
      labels:
        app: event-generator
        takipi: inject-agent
    spec:
      containers:
      - image: 432746435694.dkr.ecr.us-east-1.amazonaws.com/event-generator:latest
        name: event-generator
        imagePullPolicy: Always
