apiVersion: apps/v1
kind: Deployment
metadata:
  name: overops-collector-deployment
  labels:
    app: overops-collector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: overops-collector
  template:
    metadata:
      labels:
        app: overops-collector
    spec:
      containers:
        - name: overops-collector
          image: overops-collector:latest
          ports:
            - containerPort: 6060
          volumeMounts:
            - mountPath: /opt/takipi/private
              name: overops-private-volume
          imagePullPolicy: Never
      volumes:
        - name: overops-private-volume
          secret:
            secretName: overops-collector
